project:
  type: website
  output-dir: docs

website:
  title: "El Paso Crime Lab"
  favicon: about_logo.png
  navbar:
    background: primary
    search: false
    left:
      - text: "About"
        href: index.html
      - text: "Driving While Intoxicated"
        menu:
          - text: "Overview"
            href: dwi_home.html
          - text: "Local Research on Impaired Driving"
            href: dwi_protocol.html
          - text: "Study: Does Public Shaming Deter Drunk Driving?"
            href: dwi_friday_study.html
          - text: "Alcohol-Related Crash Dashboard"
            href: crash_dashboard.html
          - text: "Latest Local News"
            href: dwi_news.html
    right:
      - text: "Subscribe for Updates"
        href: subscribe.html
      - text: "Contact"
        href: contact.html

format:
  html:
    theme: default
    css: styles2.css
    toc: false
    


editor: source

  