project:
  type: website
  output-dir: docs

website:
  title: "El Paso Crime Lab"
  navbar:
    background: primary
    search: true
    left:
      - text: "Dashboards"
        menu:
        - text: "Driving While Intoxicated"
          href: crash_dashboard.html
    right:
      - text: "Contact"
        href: https://mattduran12.github.io

format:
  html:
    theme: cosmo
    css: styles2.css
    toc: false

editor: source

  