project:
  type: website
  output-dir: docs

website:
  title: "El Paso Crime Lab"
  navbar:
    background: primary
    search: false
    left:
      - text: "About"
        href: index.html
      - text: "Research on Driving While Intoxicated"
        menu:
          - text: "Home"
            href: research_drunkdriving.html
          - text: "Drunk Driving Surveillance Dashboard"
            href: crash_dashboard.html
          - text: "Study: Does Public Shaming Deter Drunk Driving?"
            href: dwi_friday_study.html
          - text: "Latest Local News on DWI"
            href: dwi_news.html
    right:
      - text: "Subscribe for Updates"
        href: subscribe.html
      - text: "Contact"
        href: contact.html

format:
  html:
    theme: cosmo
    css: styles2.css
    toc: false

editor: source

  