---
title: "About Open Criminology El Paso"
format:
  html:
    grid:
      margin-width: 450px
      body-width: 600px
    theme: cosmo
---

## Purpose

The purpose of Open Criminology El Paso is to share criminal justice-related research conducted in the El Paso region. By documenting these efforts, city officials and community members can rely on evidence-based findings to inform public policy and practices.

## How This Started

    A right of passage for graduate students in a social science program is to produce original research, usually in the form of a capstone paper or thesis. The official purpose varies, but the idea is for the student to demonstrate expertise and knowledge on a specific topic. When I was a graduate student (here is the only plug I'll give to my own research), [my thesis project](https://scholarworks.utep.edu/open_etd/3786/) was a study on how police officers perceive negative media attention, their agency, and their own authority. I'll save you a few hours and tell you that the findings suggest negative media attention impacts how officers view their own authority, but how they view their agency matters more.

    Like other students, more time than I am willing to admit went into completing my research project. If you count the hours I spent designing the survey, jumping through bureaucratic hurdles to get approval, figuring out how to calculate a correlation, and revising my writing for clarity, it took 15 days, 500 nights, and a concerning amount of caffeine. (Do consider visiting your local coffee shop on Sunday and purchasing a drink for the sleep-deprived student you find staring at their laptop and rubbing their temples. Bonus points if you tell them their research is going to change the world and to not use AI to write their papers).

    There are several carrots for getting that research project done. The obvious one is getting to wear a cool gown and march around the Don Haskins Center like it's your quinceñera. Another important one is being able to click on a new box for educational attainment in the online job application. The reward could also be doing something no one else in your family had the opportunity to do. In that case, you are a role model to the people aroud you, even the old ones (It's never too late).

    A less appreciated carrot, and what inspired Open Criminology El Paso, is getting other people to read your writing. Is it vain? Absolutely. As vain as a new parent who wants to show off their baby---writing a research paper is no less. Just like a new child, however, the magic eventually wanes, and you realize no one cares (for children, around age 8. I'm kidding. Everyone still cares about you). In all truth, most people will never read your thesis or capstone paper, even your own mother, who promised. If you are lucky, your mom will read the introduction section because you spent the most time making it enjoyable to read. If you don't believe me, ask her what she thought about your findings (by the way, that's what you look and sound like in class when you don't do the assigned readings).

    The fault is not with our moms, dads, grandmas, grandpas, or anyone we hoped would read our research. The fault is in the tradition of academic writing---researchers often write for other researchers. While there is value in having someone familiar with The Code review your work, writing in The Code is at the expense of the community our research intends to serve. In other words, the researcher who is double-checking your traffic stop analysis praises you for including an interaction term, but the city official who needs to know what you found and how it impacts their decisions is already moving on.

    Open Criminology El Paso seeks to address that reality. My hope for this website is to document local research being done in the city, and to translate the material into everyday language, or what I consider everyday language (it's more fun my way). I will do my best, but my best might not be good enough. I may resort to jargon or really goof in explaining something. Have pity on me, please, and let me know via [email](mduran29@asu.edu) where you stopped reading. You are my audience, as much as my editor. Thank you, and I hope this is useful.
